name: Build ImmortalWrt 25.12 for RAX3000M

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware
        run: |
          # 克隆 25.12 仓库源码
          git clone https://github.com/tfnhui/immortalwrt-mt798x-25.12.git openwrt
          cd openwrt

          # 直接复制配置文件
          cp ../.github/workflows/.config .config

          # 更新 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # 生成完整配置
          make defconfig
          
          # 在 'make defconfig' 之后执行
          grep CONFIG_PACKAGE_luci-app-openclash .config || { echo "::error::OpenClash is NOT selected!"; exit 1; }

          # 下载编译所需的源码包
          make download -j$(nproc)

          # 开始编译
          make -j$(nproc)
          
          # 删除 packages 目录（不需要上传）
          rm -rf bin/targets/mediatek/filogic/packages
          
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-25.12-rax3000m-firmware
          path: openwrt/bin/targets/mediatek/filogic/
          if-no-files-found: warn
